apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: pedrogimenezsilva/fiap_tech_challenge:v1.0.0

