apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: pedrogimenezsilva/fiap_tech_challenge_admin:v1.0.0

