apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  namespace: admin
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" 
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" 
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
