apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: video-extractor-role
  namespace: video
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods", "configmaps", "services", "endpoints", "replicasets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: video-extractor-rolebinding
  namespace: video
subjects:
  - kind: ServiceAccount
    name: video-extractor-sa
    namespace: video
roleRef:
  kind: Role
  name: video-extractor-role
  apiGroup: rbac.authorization.k8s.io
