apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: video-extractor-role
  namespace: video
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-app-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: video-extractor-sa
    namespace: video
roleRef:
  kind: Role
  name: video-extractor-role
  apiGroup: rbac.authorization.k8s.io
