apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-extractor-sa
  namespace: video
  annotations:
    eks.amazonaws.com/role-arn: kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode

