apiVersion: v1
kind: Service
metadata:
  name: video-extractor-svc
  namespace: video
spec:
  selector:
    app: video-extractor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # O tráfego virá pelo Ingress e não diretamente pelo LoadBalancer
