apiVersion: v1
kind: Service
metadata:
  name: video-extractor-svc
  namespace: video
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # Define que será um ALB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # ALB acessível pela internet
spec:
  selector:
    app: video-extractor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Tipo LoadBalancer, que cria um ALB automaticamente
